import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "../components/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <title>Esta es mi nueva aplicacion con la cual hare trades</title>
      <body>
        <Navigation/>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
